[build]
  command = "pnpm build"
  functions = "dist/netlify/functions"

[[redirects]]
  from = "/v1/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["jsdom"]


[functions."*"]
  ignored_files = ["**/*.d.ts", "**/*.d.ts.map"]